// android
const String ANDROID_AD_BANNER_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String ANDROID_AD_INTERSTITIAL_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String ANDROID_AD_NATIVE_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String ANDROID_AD_NATIVE_BANNER_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
// ios
const String IOS_AD_BANNER_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String IOS_AD_INTERSTITIAL_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String IOS_AD_NATIVE_PLACEMENT_ID = "YOUR_PLACEMENT_ID";
const String IOS_AD_NATIVE_BANNER_PLACEMENT_ID = "YOUR_PLACEMENT_ID";


